### ISSUE TITLE
Issues creating images with newer libnds

### ISSUE THREAD

**Issue by tediousinsomnia** [Patater/manual#5]
Images created with the newest version of libnds yields distorted and incorrect images

![chapter_6-sprites](https://cloud.githubusercontent.com/assets/26483634/24042353/380e6c28-0ad7-11e7-9178-52fdb6d06af7.png)
![chapter_7-game](https://cloud.githubusercontent.com/assets/26483634/24042355/380eb052-0ad7-11e7-977e-daf6f77f7c8c.png)
![chapter_8-input](https://cloud.githubusercontent.com/assets/26483634/24042354/380e8e92-0ad7-11e7-95b0-0b8c5433ccc8.png)
![chapter_5-backgrounds](https://cloud.githubusercontent.com/assets/26483634/24042356/380f7532-0ad7-11e7-9485-63ddf4d18d5f.png)

**Comment by Patater** [comment]
What's your development platform?

I was not able to reproduce the issue with the following platform.
- Host OS: macOS 10.12.4
- devkitARM r46
- libnds 1.6.2
- desmume 0.9.11

**Comment by SnakeDoctors** [comment]
I had the same issue with the top screen displaying the wrong colors.
The problem was that grit was generating 512 bytes palettes for the sprites, so the moon palette was overwriting the backdrop color of the 2D sub engine's BG palette RAM, that's why the background of the image is white.

I fixed the problem by adding the parameter -pn16 to the grit files of the sprites to tell grit to create a 16 color palette.

**Comment by Patater** [comment]
> I fixed the problem by adding the parameter -pn16 to the grit files of the sprites to tell grit to create a 16 color palette.

Thanks for a solution. I've fixed this now and verified with the latest grit, libnds, and devkitARM.
